### ISSUE TITLE
Redirect Problem - Google Login

### ISSUE THREAD

**Issue by andrea-giannini** [akeeba/sociallogin#98]
Hi everyone, in my new website I'm using Google Login for my users to login. however, after they login, they get stuck

### Steps to reproduce the issue

- Created a new website
- Installed Social Login 4.4.2
- Created new credentials in Google API
- Copied the key in the plugin
- Created a login module
- Linked a redirect page called "products"

### Expected result

After login, the user should be redirected to the "products" page, as it does for users logging normally and not with google login

### Actual result

The user gets stuck here: "/component/users/methods?Itemid=101"
101 is the item id of my homepage
what the user sees, is an empty page with header and footer, but the content is completely white, contrary to the homepage with is full of content
The user can't navigate to any other page, by clicking on every menu he stays stuck
The only way is to manually log the user out form the backend

### Troubleshooting already performed

I uninstalled the social login plugin and reinstalled
I remade all the credentials in the Google API (I doubt that's the issue since the user is correctly logged in and a new user is created)

I even created a menu item "login" thinking it was a module problem, but I have the same result

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: Joomla! 4.3.1 Stable [ Bora ] 2-May-2023 16:00 GMT
* **PHP version**: 8.0.28
* **Am I using HTTPS**: Yes
* **Server Operating System**: Don't Know
* **My device's Operating System**: macOS & iOS (tried both)
* **My device's Operating System version**: macOS Monterey & iOS 16.1
* **Browser**: Firefox & Safari
* **Browser version**: Don't know

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: 10.6.12-MariaDB-log
* **Server type**: Apache
* **Server version**: Don't know
* **Hosting company / Local server**: Hostpoint
* **Server Operating System version**: Don't know

**Comment by nikosdion** [comment]
This was already addressed [in version 4.4.2](https://github.com/akeeba/sociallogin/commit/c45b925a3ed5523ae8498ccdce9e716c0a7ea4af), as long as you're using Joomla's login module. Third party login modules may not communicate the return URL correctly or at all. In this case, the redirection will be broken.

**Comment by andrea-giannini** [comment]
Hi @nikosdion , thank you for your quick answer.

I am indeed using version 4.4.2 and the standard Joomla login module. Is there anything else that might have caused this?

**Comment by andrea-giannini** [comment]
Update: I tried installing a previous version, and updating to the latest version inside joomla. Still no change.

I tired multiple times, every time after logging in with google, I get redirected to this empty page. Here are three urls from the three times I tried it:

https://my-website.com/index.php?option=com_ajax&group=sociallogin&plugin=google&format=raw&code=4%2F0AbUR2VOfL1JTlrKj7QDlMpOniDLQHwO7kv-MUZZDZPTllA5UHjCVsN-VXrTmXhCS3-J3jQ&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+openid&authuser=0&prompt=none#

https://my-website.com/index.php?option=com_ajax&group=sociallogin&plugin=google&format=raw&code=4%2F0AbUR2VMepVxem1rYDtk7KUi3idAoIsoujS5D4o6qrocgUxTJfEq2NZocj74QLBTO_OaB3Q&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&authuser=0&prompt=none#


https://my-website.com/index.php?option=com_ajax&group=sociallogin&plugin=google&format=raw&code=4%2F0AbUR2VPQCBWgQPqFyEVRXS5U0HfFfphCTzxGvH9bk7DpUqtPkydE--oHhxtkCyaHk6VFbQ&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&authuser=0&prompt=none#



from here, if I click anywhere, I stay in the same page but with this url: https://my-website.com/en/component/users/methods?Itemid=101

**Comment by andrea-giannini** [comment]
I could not solve it so I rebuilt the website!

**Comment by nikosdion** [comment]
So, it worked with the rebuilt site? Because I was not able to reproduce it with any of my dev sites (on live hosts).

**Comment by andrea-giannini** [comment]
yes it did, now everything is working fine

I have another question, where is the source file for the "Sign in with Google" sentence? I would like to change it to "Continue with Google"

**Comment by nikosdion** [comment]
You can always search for and override language strings using Joomla's Language Overrides feature. [Here's a third party tutorial on Joomla 4 language overrides](https://www.joomdev.com/language-overrides-in-joomla-4/).

The language string you are looking for is `PLG_SOCIALLOGIN_GOOGLE_LOGIN_LABEL`
